var prefixes = [
    "The",
    "Very",
    "Super",
    "Insanely",
    "Completely",
    "Awesomely",
    "Extremely",
    "Mostly",
    "Somehow",
    "Weirdly",
    "Barely",
    "Heavily",
    "Painfully",
    "Excessively",
    "Awkwardly",
    "Dramatically",
    "Perfectly",
    "Rarely",
    "Always",
    "Sometimes",
    "Somewhat",
    "Mildly",
    "Sufficiently",
    "Hardly",
    "Nearly",
    "Highly",
    "Madly",
    "Mostly",
    "Don't eat",
    "We like",
    "You",
    "We love",
    "Don't do",
    "Don't argue with",
    "One",
    "Two",
    "Three",
    "Four",
    "1",
    "2",
    "3",
    "4",
    "24",
    "89",
    "99",
    "100",
    "204"
];

var adjectives = [
    "Good",
    "Crazy",
    "Lazy",
    "Stupid",
    "Awesome",
    "Great",
    "Swabian",
    "German",
    "Tall",
    "Tiny",
    "Cute",
    "Crafty",
    "Pink",
    "Purple",
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "24 inches",
    "Rude",
    "Self-conscious",
    "Medium-rare",
    "Protectors of the",
    "Guardians of the",
    "Sexy",
    "Insane",
    "Toasted",
    "Concerned",
    "Wasted",
    "Drunken",
    "Nifty",
    "Chubby",
    "Fat",
    "Well-toned",
    "Introverted",
    "Hot",
    "Naked",
    "Nice",
    "Small",
    "Big",
    "All Hail the",
    "Intergalactic",
    "Fast",
    "Slow",
    "Dancing",
    "Hipster",
    "Illegal",
    "Flat",
    "3-dimensional",
    "Old",
    "High",
    "Bad",
    "24%",
    "50%",
    "Two Thirds",
    "Half",
    "Sweet",
    "Bitter",
    "Salty",
    "Blind",
    "Dirty",
    "Filthy",
    "Painful",
    "Fluffy",
    "Loud",
    "Quiet",
    "Dramatic",
    "Dark",
    "We love",
    "Sons of",
    "Children of the",
    "Brotherhood of the",
    "Heavy",
    "Light-weighted",
    "Concerned",
    "Nasty",
    "Naughty",
    "Nice",
    "Universal",
    "Extroverted",
    "Coding",
    "Creative",
    "Sick",
    "Smoking",
    "Tasty",
    "Selfish",
    "Relaxed",
    "Brave",
    "Black",
    "White",
    "Damaged",
    "Raging",
    "Angry",
    "Emotional",
    "Hateful",
    "Intelligent",
    "Infinite",
    "Needy",
    "Noisy",
    "Poor",
    "Pretty",
    "Real",
    "Rich",
    "Loyal",
    "Sticky",
    "Thirsty",
    "Ugly",
    "Handsome",
    "Violent",
    "Wild",
    "Funny",
    "Cursing",
    "Lit",
    "Fly",
    "Woke",
    "Savage",
    "Done",
    "Square",
    "Epic",
    "Quick",
    "Freezing",
    "Confused",
    "Sleepy",
    "Sneaky",
    "Empty",
    "Wicked",
    "Nuclear",
    "Contaminated",
    "The last",
    "Impressive",
    "Mrs.",
    "Mr.",
    "Mr. & Mrs.",
    "Unattractive",
    "End of the",
    "Never enough",
    "Bearded",
    "Shaved",
    "The Vault",
    "Guild of the",
    "New Generation of the"
];

var nouns = [
    "Koala",
    "Sloth",
    "Giraffe",
    "Dog",
    "Unicorn",
    "Panda",
    "Monkey",
    "Sheep",
    "Fox",
    "Rhino",
    "Wolf",
    "Puppy",
    "Cow",
    "Bear",
    "Bee",
    "Animal",
    "Chicken",
    "Pig",
    "Yeti",
    "Turtle",
    "Snail",
    "Zebra",
    "Penguin",
    "Squirrel",
    "Elephant",
    "Eagle",
    "Owl",

    "Koalas",
    "Sloths",
    "Giraffes",
    "Dogs",
    "Unicorns",
    "Pandas",
    "Monkeys",
    "Sheeps",
    "Foxes",
    "Rhinos",
    "Wolves",
    "Puppies",
    "Cows",
    "Bears",
    "Bees",
    "Animals",
    "Chickens",
    "Pigs",
    "Yetis",
    "Turtles",
    "Snails",
    "Zebras",
    "Penguins",
    "Squirrels",
    "Elephants",
    "Eagles",
    "Owls",

    "Moustache",
    "Brothers",
    "Caveman",
    "Moms",
    "Dads",
    "Lamp",
    "Bacon",
    "Hipster",
    "Chocolate",
    "Doctor",
    "Bratwurst",
    "Grandpa",
    "Baby",
    "Toddler",
    "Vodka",
    "Rum",
    "Beer",
    "Wine",
    "German",
    "Infinity",
    "Hat",
    "Bomb",
    "Pixel",
    "Data",
    "Bros",
    "Boy",
    "People",
    "World",
    "Love",
    "President",
    "Time",
    "Hero",
    "T-Shirt",
    "Painting",
    "Pilot",
    "Engineer",
    "Developer",
    "Dentist",
    "Firefighter",
    "Nurse",
    "Farmer",
    "Stripper",
    "Nerds",
    "Pirates",
    "Assassins",
    "Ninjas",
    "Samurai",
    "Tourist",
    "Savage",
    "Hashtag",
    "Grandma",
    "Soldier",
    "Mage",
    "Hunter",
    "Paladin",
    "Warrior",
    "Necromancer",
    "Thief",
    "Battlemage",
    "Tank",
    "Healer",
    "Ranger",
    "Alchemist",
    "Beastmaster",
    "Rogue",
    "Shaman",
    "Warlock",
    "Blacksmith",
    "Wizard",
    "Barbarian",
    "Cleric",
    "Bard",
    "Monk",
    "Fighter",
    "Crusader",
    "Arcanist",
    "Knight",
    "Priest",
    "Souls",
    "Patriot",
    "Adventurer",
    "Dwarf",
    "Human",
    "Elf",
    "Orc",
    "Undead",
    "Drunk",
    "Berserk",
    "Zombie",
    "Smoker",
    "Snow",
    "Square",
    "Beard",
    "Bottle",
    "Pie",
    "Taco",
    "Captain",
    "Sun",
    "Moon",
    "Star",
    "Suns",
    "Moons",
    "Stars",
    "Comet",
    "Space",
    "Virgins",
    "Fallout",
    "Banana",
    "Apple",
    "Lemon",
    "Lime",
    "Avocado",
    "Broccoli",
    "Cherry",
    "Kiwi",
    "Mushroom",
    "Peanut",
    "Berry",
    "Tomato",
    "Coconut",
    "Chili",
    "Bananas",
    "Apples",
    "Lemons",
    "Limes",
    "Avocados",
    "Broccolis",
    "Cherries",
    "Kiwis",
    "Mushrooms",
    "Peanuts",
    "Berries",
    "Tomatos",
    "Coconuts",
    "Chilis",
    "Hangover",
    "Drugs",

    ""
];

var companyLabel = [
    "Inc.",
    "Corporation",
    "Softworks",
    "Arts",
    "Studio",
    "Studios",
    "Industries",
    "Creatives",
    "Creations",
    "Development",
    "Games",
    "Designs",
    "Works",
    "Codeworks",
    "Productions",
    "Entertainment",
    "Interactive",
    "Team",
    "Bunch",
    "Designworks",
    "Labs",
    "Factory",
    "Manufactory",
    "Foundry",
    "Manufacturing",
    "Forge",
    "Crew",
    "Squad",
    "Horde",
    "Unit",
    "Party",
    "Mafia",
    "Artists",
    "Crafts",
    "Ltd.",
    "Electronics",
    "Animals"
];

// Calculate the number of options
var countOptions = prefixes.length * adjectives.length * nouns.length * companyLabel.length;
countOptions = countOptions.toLocaleString();
console.log (countOptions);


function generateName () {

    var chosenPrefix;
    var chosenAdjective;
    var chosenNoun;

    // Randomly choose a word
    chosenAdjective = adjectives[Math.floor(Math.random()*adjectives.length)];
    chosenNoun = nouns[Math.floor(Math.random()*nouns.length)];


    // Exceptions
    var cases = [
        "We love",
        "All Hail the",
        "Protectors of the",
        "Guardians of the",
        "Children of the",
        "Brotherhood of the",
        "Sons of",
        "24%",
        "50%",
        "24 inches",
        "The last",
        "Mrs.",
        "Mr.",
        "Mr. & Mrs.",
        "End of the",
        "Never enough",
        "The Vault",
        "Guild of the",
        "New Generation of the"
    ];

    if (cases.indexOf(chosenAdjective) != -1) { var percentagePrefix = 100; }
    else { var percentagePrefix = Math.floor(Math.random() * 100); }



    // Chance to add a Prefix
    if (percentagePrefix <= 40) { chosenPrefix = prefixes[Math.floor(Math.random()*prefixes.length)]; }
    else { chosenPrefix = ""; }


    // Put the full name into a variable
    var yourName =
        chosenPrefix +
        " " +
        chosenAdjective +
        " " +
        chosenNoun
        ;

    // Display the name in the HTML
    document.write(yourName);
}

function showCompany () {
    var chosenCompany;

    // Chance to add a Company Label
    var percentageCompany = Math.floor(Math.random() * 100);

    if (percentageCompany <= 50) { chosenCompany = companyLabel[Math.floor(Math.random()*companyLabel.length)]; }
    else { chosenCompany = ""; }

    // Display the Label in the HTML
    document.write(chosenCompany);
}
